# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  basicAction:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          sleep 10
          echo test, and deploy your project.
      - name: Throw error to testing if other action block
        run: |
          echo "::error::this is error message"
          exit 1
  

  dependAction:
    runs-on: ubuntu-latest
    needs: basicAction
    steps:
      - name: Running depends jobs
        run: echo running depends jobs!!

  dependActionSuccess:
    runs-on: ubuntu-latest
    needs: basicAction
    if: needs.basicAction.result == 'success'
    steps:
      - name: Running depends jobs when need job pass
        run: echo running depends jobs with need job pass!!

  dependActionFailure:
    runs-on: ubuntu-latest
    needs: basicAction
    if: needs.basicAction.result == 'failure'
    steps:
      - name: Running depends jobs when needs job fail
        run: echo running depends jobs with need job fail!!
  
  notDependAction:
    runs-on: ubuntu-latest
    steps:
      - name: run a non depends jobs
        run: echo running a not depends steps
