# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  basicAction:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          sleep 10
          echo test, and deploy your project.
  
  dependAction:
    runs-on: ubuntu-latest
    needs: basicAction
    steps:
      - name: Running depends jobs
        run: echo running depends jobs!!
  
  notDependAction:
    runs-on: ubuntu-latest
    steps:
      - name: run a non depends jobs
        run: echo running a not depends steps
