name: testing custom Action call

on:
  push:
    branches: ["main"]

jobs:
  customJSJob:
    runs-on: ubuntu-latest
    steps:
      - name: calling custom js action
        id: customStep
        uses: naresh7991/demo-custom-js-action@v1
        with:
          message: This action used by ${{ github.actor }}
      
      - name: print custom step output
        run: echo "printing the time ${{ steps.customStep.outputs.time }}"
      
      - name: print custom step message
        run: echo "printing the custom message ${{ steps.customStep.outputs.greeting }}"
  
  customDockerJob:
    runs-on: ubuntu-latest
    steps:
      - name: calling custom docker action
        id: customStep
        uses: naresh7991/github-docker-action-demo@709d80ddea0aad02e85b9103c66b0af854bb026f
        with:
          message: This action used by ${{ github.actor }} && ${{ github.repository }}
      
      - name: print docker action output
        run: |
          echo " printing docker action output: ${{ steps.customStep.outputs.time }}"
