name: testing custom Action call

on:
  push:
    branches: ["main"]

jobs:
  customJSJob:
    runs-on: ubuntu-latest
    steps:
      - name: calling custom js action
        id: customStep
        uses: naresh7991/demo-custom-js-action@v1
        with:
          message: This action used by ${{ github.actor }}
      
      - name: print custom step output
        run: echo "printing the time ${{ steps.customStep.outputs.time }}"
      
      - name: print custom step message
        run: echo "printing the custom message ${{ steps.customStep.outputs.greeting }}"
  
  customDockerJob:
    runs-on: ubuntu-latest
    steps:
      - name: calling custom docker action
        id: customStep
        uses: naresh7991/github-docker-action-demo@877b2f7e9d45de062241a396958d4f79bfbe35d2
        with:
          message: This action used by ${{ github.actor }} && ${{ github.repository }}
      
      - name: print docker action output
        run: |
          echo " printing docker action output: ${{ steps.customStep.outputs.time }}"

  customCompositeJob:
    runs-on: ubuntu-latest
    steps:
      - name: custom composite step
        id: customCompositeAction
        uses:  naresh7991/github-action-composite-demo@2a8f22aec5a16741659b65586f1b933455bc9007
        with:
          message: This is custom message from username ${{github.actor}} and from repo ${{github.repository}}
      
      - name:
        run: echo "printing time of custom composite action- ${{ steps.customCompositeAction.outputs.time }}"