name: testing custom Action call

on:
  push:
    branches: ["main"]

jobs:
  customJob:
    runs-on: ubuntu-latest
    steps:
      - name: calling custom js action
        id: customStep
        uses: naresh7991/demo-custom-js-action@v1
        with: This action used by ${{ github.actor }}
      
      - name: print custom step output
        run: echo printing the time: ${{ steps.customStep.output.time }}
      
      - name: print custom step message
        run: echo printing the custom message: ${{ steps.customStep.output.greeting }}